/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0db62c53-c9d4-4d51-b6e2-e5ee1c75d0ba",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_TD29cU2Q4",
    "aws_user_pools_web_client_id": "3knmk9u50p802l9km4o8jk6ce7",
    "oauth": {}
};


export default awsmobile;
